#
# Copyright © 2023 Les Hazlewood
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
name: CI

on:
  pull_request: # all pull requests
  push:
    branches:
      - main

env:
  MVN_CMD: mvn --no-transfer-progress -B

jobs:
  oracle:
    strategy:
      matrix:
        java: [ '21' ]
    runs-on: 'ubuntu-latest'
    name: jdk-${{ matrix.java }}-oracle
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: oracle-actions/setup-java@v1
        with:
          release: ${{ matrix.java }}
      - name: Build
        # run a full build, just as we would for a release (i.e. the `ossrh` profile), but don't use gpg
        # to sign artifacts, since we don't want to mess with storing signing credentials in CI:
        run: ${{env.MVN_CMD}} verify -Possrh -Dgpg.skip=true

  temurin:
    strategy:
      matrix:
        java: [ '21' ]
    runs-on: 'ubuntu-latest'
    name: jdk-${{ matrix.java }}-temurin
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: 'maven'
          check-latest: true
      - name: Build
        # run a full build, just as we would for a release (i.e. the `ossrh` profile), but don't use gpg
        # to sign artifacts, since we don't want to mess with storing signing credentials in CI:
        run: ${{env.MVN_CMD}} verify -Possrh -Dgpg.skip=true

  zulu:
    strategy:
      matrix:
        java: [ '21' ]
    runs-on: 'ubuntu-latest'
    env:
      JDK_MAJOR_VERSION: ${{ matrix.java }}
    name: jdk-${{ matrix.java }}-zulu
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          cache: 'maven'
          check-latest: true
      - name: Build
        # run a full build, just as we would for a release (i.e. the `ossrh` profile), but don't use gpg
        # to sign artifacts, since we don't want to mess with storing signing credentials in CI:
        run: ${{env.MVN_CMD}} verify -Possrh -Dgpg.skip=true

  # ensure all of our files have the correct/updated license header
  license-check:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # avoid license plugin history warnings (plus it needs full history)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          check-latest: true
      - name: License Check
        # This adds about 1 minute to any build, which is why we don't want to do it on every other build:
        run: ${{env.MVN_CMD}} license:check

  code-coverage:
    # (commented out for now - see the comments in 'Wait to start' below for why.  Keeping this here as a placeholder
    # as it may be better to use instead of an artificial delay once we no longer need to build on JDK 7):
    #needs: zulu # wait until others finish so a coverage failure doesn't cancel others accidentally
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: 'maven'
          check-latest: true
      #      - name: Wait to start
      #        # wait a little to start: code coverage usually only takes about 1 1/2 minutes.  If coverage fails, it will
      #        # cancel the other running builds, and we don't want that (because we want to see if jobs fail due to
      #        # build issues, not due to the code-coverage job causing the others to cancel).  We could have used the
      #        # 'need' property (commented out above), and that would wait until all the other jobs have finished before
      #        # starting this one, but that introduces unnecessary (sometimes 2 1/2 minute) delay, whereas delaying the
      #        # start of the code coverage checks a bit should allow everything to finish around the same time without having
      #        # much of an adverse effect on the other jobs above.
      #        run: sleep 90s
      #        shell: bash
      - name: Code Coverage
        run: ${{env.MVN_CMD}} clover:setup test && ${{env.MVN_CMD}} -pl . clover:clover clover:check
